
camper = []
trainer = []
resultadoSandbox = []
ruta =[]
modulo =[]
temario= []
notaTeorica =[]
notaPractica = []
estados = ["En proceso de ingreso", "Inscrito", "Aprobado","Cursando", "Graduado", "Expulsado", "Retirado","Riesgo"]