
camper = []
trainer = []
resultadoSandbox = []
rutas =[]
modulos =[]
temario= []
prueba=[]
estados = ["En proceso de ingreso", "Inscrito", "Aprobado","Cursando", "Graduado", "Expulsado", "Retirado","Riesgo"]
areas = []
camperIns = []